import { ApiError, body, database, json, run, session, type PagesContext } from '../../../_shared';

const STATUSES = ['published', 'unlisted', 'taken_down', 'archived'] as const;
const SOURCE_TYPES = ['original', 'community', 'external'] as const;
const UUID_RE = /^[0-9a-f-]{36}$/;

function text(value: unknown, max: number): string | null { if (value == null) return null; if (typeof value !== 'string') throw new ApiError(400, 'Invalid text field.'); const v=value.trim(); return v ? v.slice(0,max) : null; }
function url(value: unknown, label: string): string | null { if (value == null || value === '') return null; if (typeof value !== 'string') throw new ApiError(400, `${label} must be a URL.`); let u: URL; try { u=new URL(value.trim()); } catch { throw new ApiError(400, `${label} must be a valid URL.`); } if (u.protocol!=='https:' || u.username || u.password || !u.hostname.includes('.') || /^(localhost|127\\.|10\\.|192\\.168\\.|169\\.254\\.|172\\.(1[6-9]|2[0-9]|3[01])\\.)/i.test(u.hostname)) throw new ApiError(400, `${label} must be a public https URL.`); return u.toString(); }
function uuid(value: unknown, label: string, nullable=false): string | null { if (value == null || value === '') { if(nullable) return null; throw new ApiError(400, `${label} is required.`); } const v=String(value); if(!UUID_RE.test(v)) throw new ApiError(400, `Bad ${label}.`); return v; }
function slugify(value: string): string { return value.toLowerCase().normalize('NFKD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||'track'; }
async function uniqueSlug(sql:any, desired:string, excludeId:string):Promise<string>{const base=slugify(desired);for(let i=0;i<40;i++){const candidate=i?`${base}-${i+1}`:base;const rows=await sql.query(`SELECT 1 FROM tracks WHERE slug=$1 AND id<>$2`,[candidate,excludeId]);if(!rows[0])return candidate;}return `${base}-${crypto.randomUUID().slice(0,6)}`;}
function providerForExternal(raw:string):string { const host=new URL(raw).hostname.toLowerCase(); if(host==='youtu.be'||host==='youtube.com'||host.endsWith('.youtube.com'))return'youtube'; if(host==='soundcloud.com'||host.endsWith('.soundcloud.com'))return'soundcloud'; return'other'; }
function mimeForAudio(raw:string):string|null{const path=new URL(raw).pathname.toLowerCase();const map:Record<string,string>={'.mp3':'audio/mpeg','.m4a':'audio/mp4','.aac':'audio/aac','.ogg':'audio/ogg','.oga':'audio/ogg','.opus':'audio/ogg','.wav':'audio/wav','.flac':'audio/flac','.webm':'audio/webm'};for(const [ext,mime] of Object.entries(map))if(path.endsWith(ext))return mime;return null;}
async function assertArtist(sql:any,id:string){if(!(await sql.query(`SELECT 1 FROM artists WHERE id=$1`,[id]))[0])throw new ApiError(400,'Choose an existing artist.');}
async function assertRelease(sql:any,id:string|null){if(id&&!(await sql.query(`SELECT 1 FROM albums WHERE id=$1`,[id]))[0])throw new ApiError(400,'Choose an existing release.');}
async function assertLicense(sql:any,id:string|null){if(id&&!(await sql.query(`SELECT 1 FROM licenses WHERE id=$1`,[id]))[0])throw new ApiError(400,'Unknown license.');}
async function syncGenres(sql:any,id:string,names:unknown){if(!Array.isArray(names))return;await sql.query(`DELETE FROM track_genres WHERE track_id=$1`,[id]);const seen=new Set<string>();for(const raw of names.slice(0,8)){if(typeof raw!=='string')continue;const name=raw.trim().slice(0,40);if(!name)continue;const gid=slugify(name).slice(0,40);if(seen.has(gid))continue;seen.add(gid);await sql.query(`INSERT INTO genres(id,name) VALUES($1,$2) ON CONFLICT(id) DO NOTHING`,[gid,name]);await sql.query(`INSERT INTO track_genres(track_id,genre_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[id,gid]);}}
async function syncLinks(sql:any,id:string,links:unknown){if(!Array.isArray(links))return;await sql.query(`DELETE FROM entity_links WHERE entity_kind='track' AND entity_id=$1`,[id]);let position=0;for(const raw of links.slice(0,12)){if(!raw||typeof raw!=='object')continue;const item=raw as Record<string,unknown>;const linkUrl=url(item.url,'Link');if(!linkUrl)continue;const provider=text(item.provider,30)||providerForExternal(linkUrl);const label=text(item.label,40)||provider;await sql.query(`INSERT INTO entity_links(id,entity_kind,entity_id,provider,label,url,position) VALUES($1,'track',$2,$3,$4,$5,$6)`,[crypto.randomUUID(),id,provider,label,linkUrl,position++]);}}
async function syncSources(sql:any,id:string,audioUrl:string|null,externalUrl:string|null){await sql.query(`DELETE FROM track_sources WHERE track_id=$1`,[id]);if(audioUrl)await sql.query(`INSERT INTO track_sources(id,track_id,provider,kind,url,mime_type,storage,priority,source_type,availability) VALUES($1,$2,'other','direct_url',$3,$4,'manual-url',0,'remote','available')`,[crypto.randomUUID(),id,audioUrl,mimeForAudio(audioUrl)]);if(externalUrl)await sql.query(`INSERT INTO track_sources(id,track_id,provider,kind,url,storage,priority,source_type,availability) VALUES($1,$2,$3,'external_link',$4,'external',10,'external','available')`,[crypto.randomUUID(),id,providerForExternal(externalUrl),externalUrl]);}
async function readTrack(sql:any,id:string){const rows:any[]=await sql.query(`SELECT t.*,a.name artist_name,a.slug artist_slug,al.title album_title,al.slug album_slug,al.artwork_url album_artwork,l.name license_name FROM tracks t JOIN artists a ON a.id=t.artist_id LEFT JOIN albums al ON al.id=t.album_id LEFT JOIN licenses l ON l.id=t.license_id WHERE t.id=$1`,[id]);if(!rows[0])throw new ApiError(404,'Track not found.');const row=rows[0];const [sources,genres,links]=await Promise.all([sql.query(`SELECT kind,url,mime_type FROM track_sources WHERE track_id=$1 ORDER BY priority`,[id]),sql.query(`SELECT g.id,g.name FROM track_genres tg JOIN genres g ON g.id=tg.genre_id WHERE tg.track_id=$1 ORDER BY g.name`,[id]),sql.query(`SELECT provider,label,url FROM entity_links WHERE entity_kind='track' AND entity_id=$1 ORDER BY position`,[id])]);const direct=(sources as any[]).find(s=>s.kind==='direct_url');const external=(sources as any[]).find(s=>s.kind!=='direct_url');return {track:{id:row.id,slug:row.slug,title:row.title,status:row.status,sourceType:row.source_type,trackNo:row.track_no,duration:row.duration_seconds,description:row.description??null,artworkUrl:row.artwork_url??null,inheritedArtworkUrl:row.album_artwork??null,explicit:Boolean(row.explicit),licenseId:row.license_id??null,licenseName:row.license_name??null,rightsHolder:row.rights_holder??null,credits:row.credits??null,attributionText:row.attribution_text??null,territory:row.territory??'worldwide',rightsNotes:row.rights_notes??null,streamingPermission:row.streaming_permission??true,distributionPermission:row.distribution_permission??false,artistId:row.artist_id,artist:{id:row.artist_id,name:row.artist_name,slug:row.artist_slug},releaseId:row.album_id??null,release:row.album_id?{id:row.album_id,title:row.album_title,slug:row.album_slug}:null,playCount:Number(row.play_count??0),createdAt:row.created_at,updatedAt:row.updated_at,audioUrl:direct?.url??null,externalUrl:external?.url??null,mimeType:direct?.mime_type??null,genres,links}};}
async function ensureAdmin(c:PagesContext){const u=await session(c,true);if(u!.effectiveRole!=='admin')throw new ApiError(403,'Administrator access required.');return u!;}

export const onRequest = (c:PagesContext) => run(c, async()=>{const admin=await ensureAdmin(c);void admin;const id=c.params.id;if(!id||!UUID_RE.test(id))throw new ApiError(400,'Bad track id.');const sql=await database(c.env);
  if(c.request.method==='GET') return json(await readTrack(sql,id));
  if(c.request.method==='DELETE'){const rows=await sql.query(`DELETE FROM tracks WHERE id=$1 RETURNING id`,[id]);if(!rows[0])throw new ApiError(404,'Track not found.');return json({ok:true});}
  if(c.request.method!=='PATCH') return json({error:'Method not allowed.'},405);
  const b=await body(c.request);const currentRows:any[]=await sql.query(`SELECT * FROM tracks WHERE id=$1`,[id]);if(!currentRows[0])throw new ApiError(404,'Track not found.');const current=currentRows[0];
  const title=b.title===undefined?current.title:text(b.title,160);if(!title)throw new ApiError(400,'Title is required.');
  const artistId=b.artistId===undefined?current.artist_id:uuid(b.artistId,'artist id')!;await assertArtist(sql,artistId);
  const releaseId=b.releaseId===undefined?current.album_id:uuid(b.releaseId,'release id',true);await assertRelease(sql,releaseId);
  const licenseId=b.licenseId===undefined?current.license_id:text(b.licenseId,40);await assertLicense(sql,licenseId);
  const slug=b.slug===undefined?current.slug:await uniqueSlug(sql,String(b.slug||title),id);
  const duration=b.duration===undefined?current.duration_seconds:(b.duration==null?null:Number(b.duration));if(duration!=null&&(!Number.isInteger(duration)||duration<0||duration>86400))throw new ApiError(400,'Duration must be a whole number of seconds.');
  const trackNo=b.trackNo===undefined?current.track_no:(b.trackNo==null?null:Number(b.trackNo));if(trackNo!=null&&(!Number.isInteger(trackNo)||trackNo<0||trackNo>999))throw new ApiError(400,'Track number is invalid.');
  const artworkUrl=b.artworkUrl===undefined?current.artwork_url:url(b.artworkUrl,'Artwork URL');
  const audioUrl=b.audioUrl===undefined?null:url(b.audioUrl,'Audio URL');
  const externalUrl=b.externalUrl===undefined?null:url(b.externalUrl,'External URL');
  const status=b.status===undefined?current.status:(typeof b.status==='string'&&STATUSES.includes(b.status as any)?b.status: (()=>{throw new ApiError(400,'Invalid status.');})());
  const sourceType=b.sourceType===undefined?current.source_type:(typeof b.sourceType==='string'&&SOURCE_TYPES.includes(b.sourceType as any)?b.sourceType:(()=>{throw new ApiError(400,'Invalid source type.');})());
  await sql.query(`UPDATE tracks SET slug=$2,title=$3,artist_id=$4,album_id=$5,track_no=$6,duration_seconds=$7,artwork_url=$8,description=$9,license_id=$10,rights_holder=$11,credits=$12,explicit=$13,status=$14,source_type=$15,attribution_text=$16,territory=$17,rights_notes=$18,streaming_permission=$19,distribution_permission=$20,updated_at=now() WHERE id=$1`,[id,slug,title,artistId,releaseId,trackNo,duration,artworkUrl,text(b.description,2000) ?? current.description,licenseId,text(b.rightsHolder,160) ?? current.rights_holder,text(b.credits,600) ?? current.credits,typeof b.explicit==='boolean'?b.explicit:current.explicit,status,sourceType,text(b.attributionText,300) ?? current.attribution_text,text(b.territory,60) || current.territory || 'worldwide',text(b.rightsNotes,600) ?? current.rights_notes,typeof b.streamingPermission==='boolean'?b.streamingPermission:current.streaming_permission,typeof b.distributionPermission==='boolean'?b.distributionPermission:current.distribution_permission]);
  await syncSources(sql,id,audioUrl,externalUrl);if(b.genres!==undefined)await syncGenres(sql,id,b.genres);if(b.links!==undefined)await syncLinks(sql,id,b.links);if(current.album_id&&current.album_id!==releaseId)await sql.query(`UPDATE albums SET updated_at=now() WHERE id=$1`,[current.album_id]);if(releaseId)await sql.query(`UPDATE albums SET updated_at=now() WHERE id=$1`,[releaseId]);return json(await readTrack(sql,id));
});
