/**
 * ResonTune API server.
 *
 * Serves /api/* (JSON) and /media/* (seed audio with HTTP Range support).
 * In production it also serves the built client from dist/.
 *
 * Abuse resistance built in:
 *  - bounded JSON bodies
 *  - per-IP rate limits (general + stricter for writes)
 *  - server-side validation on every mutation (zod)
 *  - pagination bounds on every list endpoint
 *  - cache headers on public catalog reads
 *  - no credentials ever sent to the client
 */
import express from 'express';
import cookieParser from 'cookie-parser';
import rateLimit from 'express-rate-limit';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { migrate } from './db/index.ts';
import { attachUser, authRouter } from './auth.ts';
import { catalogRouter } from './routes/catalog.ts';
import { playlistsRouter } from './routes/playlists.ts';
import { meRouter } from './routes/me.ts';
import { moderationRouter } from './routes/moderation.ts';
import { HttpError } from './util/http.ts';
import { seedIfEmpty } from './seed/seed.ts';
import { playRouter } from './routes/play.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.API_PORT ?? process.env.PORT ?? 8787);

async function main() {
  await migrate();
  await seedIfEmpty();

  const app = express();
  app.disable('x-powered-by');
  app.set('trust proxy', 1); // behind Cloudflare/reverse proxy in production

  app.use(express.json({ limit: '64kb' })); // bounded payloads
  app.use(cookieParser());

  /* ------------------------------ rate limits ----------------------------- */

  const generalLimiter = rateLimit({
    windowMs: 60_000,
    limit: 300,
    standardHeaders: 'draft-7',
    legacyHeaders: false,
    message: { error: 'Too many requests. Please slow down.' },
  });
  const writeLimiter = rateLimit({
    windowMs: 60_000,
    limit: 40,
    standardHeaders: 'draft-7',
    legacyHeaders: false,
    message: { error: 'Too many changes at once. Please slow down.' },
  });
  const authLimiter = rateLimit({
    windowMs: 15 * 60_000,
    limit: 25,
    standardHeaders: 'draft-7',
    legacyHeaders: false,
    message: { error: 'Too many sign-in attempts. Try again later.' },
  });

  app.use('/api', generalLimiter);
  app.use('/api', (req, res, next) => {
    if (req.method !== 'GET' && req.method !== 'HEAD') return writeLimiter(req, res, next);
    next();
  });
  app.use('/api/auth/dev-login', authLimiter);
  app.use('/api/auth/github', authLimiter);

  /* --------------------------------- auth --------------------------------- */

  app.use('/api', attachUser);
  app.use('/api/auth', authRouter());

  /* --------------------------- cache-aware reads --------------------------- */

  app.use('/api', (req, res, next) => {
    if (req.method === 'GET' && !req.path.startsWith('/auth') && !req.path.startsWith('/me')) {
      res.setHeader('Cache-Control', 'public, max-age=15, stale-while-revalidate=60');
    } else {
      res.setHeader('Cache-Control', 'no-store');
    }
    next();
  });

  /* -------------------------------- routes -------------------------------- */

  app.use('/api', catalogRouter());
  app.use('/api/play', playRouter());
  app.use('/api/playlists', playlistsRouter());
  app.use('/api/me', meRouter());
  app.use('/api/moderation', moderationRouter());

  app.get('/api/health', (_req, res) => res.json({ ok: true, name: 'resontune' }));

  /* ------------------------- media (seed audio) --------------------------- */
  // Demo catalog audio is original CC0 material generated by
  // scripts/generate-audio.cjs and served with Range support so seeking
  // works. Real deployments point track_sources at object storage / a CDN.

  const mediaDir = path.resolve(__dirname, '../media/audio');
  app.get('/media/audio/:file', (req, res) => {
    const file = String(req.params.file);
    if (!/^[a-z0-9-]+\.mp3$/.test(file)) return void res.status(400).end();
    const full = path.join(mediaDir, file);
    if (!full.startsWith(mediaDir) || !fs.existsSync(full)) return void res.status(404).end();
    const stat = fs.statSync(full);
    const range = req.headers.range;
    res.setHeader('Accept-Ranges', 'bytes');
    res.setHeader('Content-Type', 'audio/mpeg');
    res.setHeader('Cache-Control', 'public, max-age=86400, immutable');
    if (range) {
      const m = /^bytes=(\d*)-(\d*)$/.exec(range);
      if (m) {
        const start = m[1] ? parseInt(m[1], 10) : 0;
        const end = m[2] ? Math.min(parseInt(m[2], 10), stat.size - 1) : stat.size - 1;
        if (start <= end && start < stat.size) {
          res.status(206);
          res.setHeader('Content-Range', `bytes ${start}-${end}/${stat.size}`);
          res.setHeader('Content-Length', end - start + 1);
          return void fs.createReadStream(full, { start, end }).pipe(res);
        }
        res.status(416).setHeader('Content-Range', `bytes */${stat.size}`);
        return void res.end();
      }
    }
    res.setHeader('Content-Length', stat.size);
    fs.createReadStream(full).pipe(res);
  });

  /* --------------------------- static (production) ------------------------- */

  const dist = path.resolve(__dirname, '../dist');
  if (fs.existsSync(dist)) {
    app.use(express.static(dist, { maxAge: '1h', index: false }));
    app.get(/^\/(?!api|media).*/, (_req, res) => {
      res.sendFile(path.join(dist, 'index.html'));
    });
  }

  /* ------------------------------ error handling --------------------------- */

  app.use('/api', (_req, _res, next) => next(new HttpError(404, 'Not found.')));
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  app.use((err: any, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
    const status = err instanceof HttpError ? err.status : 500;
    if (status >= 500) console.error('[api]', err);
    res.status(status).json({ error: err.message ?? 'Server error.' });
  });

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`[resontune] API listening on http://0.0.0.0:${PORT}`);
  });
}

main().catch((err) => {
  console.error('Failed to start ResonTune server:', err);
  process.exit(1);
});
